# ASP.NET Core
- task: ServiceFabricDeploy@1
  inputs:
    applicationPackagePath: '$(build.artifactstagingdirectory)\applicationpackage'
    serviceConnectionName: 'Service Fabric'
    overwriteBehavior: 'SameAppTypeAndVersion'
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
